language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install .
# command to run tests
script: pytest --flake8